###
POST http://localhost:3001/api/users
Content-Type:  application/json

{
    "nome": "kevin213",
    "sobrenome": "castro",
    "email": "kevin311213@castro.com",
    "password": "427"
}
###

POST http://localhost:3001/api/googleLogin
Content-Type:  application/json

{
    "nome": "kevin213",
    "sobrenome": "castro",
    "email": "oi211@example.com",
    "password": "427"
}
###
POST http://localhost:3001/api/login
Content-Type:  application/json

{
    "email": "kevin311213@castro.com",
    "password": "427"
}
###

POST http://localhost:3001/api/recurso
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtldmluMzExMjEzQGNhc3Ryby5jb20iLCJpZCI6NSwiaWF0IjoxNjc5OTYxOTUyLCJleHAiOjE2Nzk5Nzk5NTJ9.taodRSLxCuvDePyUFdfUYVWGsUKUvlrxDLY4pKtHpi8

{
  "title": "Recurso3",
  "reatype": "Ferramenta",
  "link": "https://pt.symbolab.com/",
  "targetPublic": "Médio",
  "thumb": "https://www.shutterstock.com/image-vector/man-icon-vector-260nw-1040084344.jpg",
  "knowledgeArea": "Matemática",
  "license": "Domínio Público",
  "language": "Português",
  "description": " is simply dummy text of the printing and types",
  "instructions": "Abra, insira equação veja resposta."
}


###
GET http://localhost:3001/api/users/oi@example.com HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9pQGV4YW1wbGUuY29tIiwiaWQiOjMsImlhdCI6MTY3ODg5NDk2MywiZXhwIjoxNjc4OTEyOTYzfQ.-6lBoSQnI3cT4IQVPyUZHnuPqJ2rrpPltcEivC-lAJc

###
GET http://localhost:3001/api/users/teste HTTP/1.1

###
GET http://localhost:3001/api/recurso HTTP/1.1